name:                hellok8s
version:             0.1.0.0
github:              "denibertovic/hellok8s"
license:             GPL-3.0
author:              "Deni Bertovic"
maintainer:          "deni@denibertovic.com"
copyright:           "2020 Deni Bertovic"

# extra-source-files:
# - README.md
# - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/denibertovic/hellok8s#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- bytestring
- unordered-containers
- http-media
- http-types
- mtl
- monad-logger
- servant
- servant-docs
- servant-server
- text
- wai
- wai-extra
- warp
- lucid
- servant-lucid
- hostname

library:
  source-dirs: src

executables:
  hellok8s:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hellok8s
    - warp
